/**
 * Migrations now apply themselves, and this pins the machinery that makes
 * that trustworthy.
 *
 * They used to be pasted into the Supabase SQL Editor by hand, and the record
 * of that is not hypothetical: of five applied in one session, 021 silently
 * never landed - leaving tablets chiming for two days - and 023 half-executed,
 * because the editor runs only the highlighted text when there is a selection.
 *
 * The two properties worth protecting are that the expected list cannot fall
 * behind the folder, and that a migration failure stops the deploy rather than
 * shipping code over a schema that never changed.
 */
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { EXPECTED_MIGRATIONS } from "@/lib/expected-migrations";

let passed = 0;
function test(name: string, fn: () => void) {
  try {
    fn();
    passed++;
    console.log(`  ok - ${name}`);
  } catch (err) {
    console.error(`  FAIL - ${name}`);
    console.error(err instanceof Error ? err.message : err);
    process.exitCode = 1;
  }
}

const src = (p: string) => readFileSync(new URL(`../${p}`, import.meta.url), "utf8");
const files = readdirSync(new URL("../db/migrations/", import.meta.url)).filter((f) =>
  f.endsWith(".sql")
);

console.log("the expected list cannot fall behind the folder:");

test("every migration file is expected", () => {
  // A file added without being listed would deploy and report nothing
  // missing. A health check saying "up to date" about a database that is not
  // is worse than having no check.
  for (const f of files) {
    assert.ok(EXPECTED_MIGRATIONS.includes(f), `${f} is not in EXPECTED_MIGRATIONS - run npm run build`);
  }
});

test("nothing expected has been deleted from the folder", () => {
  for (const v of EXPECTED_MIGRATIONS) {
    assert.ok(files.includes(v), `${v} is expected but no longer exists`);
  }
});

test("it is generated, not hand-maintained", () => {
  assert.match(src("lib/expected-migrations.ts"), /GENERATED by/);
  assert.match(src("package.json"), /generate-expected-migrations\.mjs && next build/);
});

console.log("\nthe runner:");

const runner = src("scripts/migrate.mjs");

test("one transaction per file, so nothing lands half-applied", () => {
  assert.match(runner, /BEGIN/);
  assert.match(runner, /ROLLBACK/);
  assert.match(runner, /COMMIT/);
});

test("a migration is recorded in the same transaction that applies it", () => {
  // This is what makes schema_migrations trustworthy where a hand-kept table
  // would not be: the record cannot drift from the database, because either
  // both happened or neither did.
  const body = runner.slice(runner.indexOf('await client.query("BEGIN")'));
  const insert = body.indexOf("INSERT INTO schema_migrations");
  const commit = body.indexOf('client.query("COMMIT")');
  assert.ok(insert > -1 && commit > -1 && insert < commit);
});

test("a failure stops the deploy", () => {
  // Shipping code whose migration just failed is the exact situation this
  // exists to prevent.
  assert.match(runner, /process\.exit\(1\)/);
  assert.match(src("package.json"), /migrate\.mjs && next build/);
});

test("migrations run BEFORE the build, not after", () => {
  const build = JSON.parse(src("package.json")).scripts["vercel-build"] as string;
  assert.ok(
    build.indexOf("migrate.mjs") < build.indexOf("next build"),
    "code must never be built against a schema that has not been migrated"
  );
});

test("an unset connection string warns rather than failing every deploy", () => {
  // Adding this script must not break deploys until somebody sets a variable -
  // a worse failure than the one it fixes. /api/health names the gap instead.
  assert.match(runner, /skipping migrations/);
  assert.doesNotMatch(runner.slice(0, runner.indexOf("const pool")), /process\.exit\(1\)/);
});

test("it insists on a session-mode connection", () => {
  // DDL plus bookkeeping inside one BEGIN/COMMIT, which the transaction-mode
  // pooler does not reliably support.
  assert.match(runner, /SESSION-mode/);
  assert.match(runner, /MIGRATION_DATABASE_URL/);
});

console.log("\nevery new table gets row level security:");

test("every table in this database has RLS enabled somewhere", () => {
  // Supabase's SQL editor warned about exactly this on 024, and the runner
  // removes that safety net - nothing will warn again. So the check moves
  // here, where it runs on every commit rather than depending on where a
  // statement happened to be typed.
  //
  // Across ALL files, not within each: RLS is a property of the database, and
  // a table created in 005 may legitimately be secured by 025. Checking
  // file-by-file would demand the fix live in the migration that is already
  // applied and must not be edited.
  const sources = ["db/schema.sql", ...files.map((f) => `db/migrations/${f}`)];
  const created = new Map<string, string>();
  const secured = new Set<string>();

  for (const rel of sources) {
    const sql = src(rel);
    // Leading-anchored: comments mention "create table" in prose, and only a
    // real statement counts.
    for (const m of sql.matchAll(/^\s*create table (?:if not exists )?([a-z_]+)/gim)) {
      if (!created.has(m[1])) created.set(m[1], rel);
    }
    for (const m of sql.matchAll(/alter table ([a-z_]+) enable row level security/gi)) {
      secured.add(m[1]);
    }
  }

  const open = [...created.entries()].filter(([t]) => !secured.has(t));
  assert.deepEqual(
    open.map(([t, f]) => `${t} (${f})`),
    [],
    "these tables are readable by anyone holding the anon key"
  );
});

console.log(`\n${passed} assertions passed.`);
